### ISSUE TITLE
Error en import bitso websocket

### ISSUE THREAD

**Issue by jonaths** [bitsoex/bitso-py#13]
Estoy intentando correr el ejemplo con websockets. Cloné el repositorio y utilice el codigo demo tal cual aparece en la documentacion y el problema surge en la primera linea:

from bitso import websocket

Y el error:

ImportError: cannot import name websocket

Hay algo mal con la documentacion? Gracias.

**Comment by mariorz** [comment]
Hola jonaths, te hace falta instalar unas dependencias, en primera instancia websocket-client pero probablemente algunas más. Si corres "python setup.py install" el script se encargara de instalar todas las dependencias necesarias.
