### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by KoenBal** [bitsoex/bitso-py#14]
Hello,

I'm unable to install the package. I tried with:
pip install git+https://github.com/bitsoex/bitso-py.git

The response I get is:
```Collecting git+https://github.com/bitsoex/bitso-py.git
  Cloning https://github.com/bitsoex/bitso-py.git to c:\users\koen_\appdata\local\temp\pip-bllmyzd9-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\koen_\AppData\Local\Temp\pip-bllmyzd9-build\setup.py", line 5, in <module>
        long_description = open('README.md').read()
      File "C:\Users\koen_\Anaconda3\envs\LambdaDeploymentPackage\TradingBotEnv\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 23407: character maps to <undefined>
```
Maybe a similar issue as this one?
https://stackoverflow.com/questions/30750843/python-3-unicodedecodeerror-charmap-codec-cant-decode-byte-0x9d
I'm on windows 10.

**Comment by mariorz** [comment]
You're using Python3, but as the docs indicate, this library is written for Python 3. There are a couple of untested PR for python 3 compatibly you might want to try :)

https://github.com/bitsoex/bitso-py/pulls
