### ISSUE TITLE
Soporte para Python 3

### ISSUE THREAD

**Issue by xiclopex** [bitsoex/bitso-py#15]
Por favor, dar soporte para Python 3
`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-10083fb0f6d1> in <module>()
----> 1 import bitso
      2 api = bitso.Api()

~/anaconda3/lib/python3.6/site-packages/bitso/__init__.py in <module>()
     51 
     52 
---> 53 from .api import Api
     54 from .bitsows import (Listener, Client)
     55 

~/anaconda3/lib/python3.6/site-packages/bitso/api.py in <module>()
     30 import time
     31 import requests
---> 32 from urlparse import urlparse
     33 from urllib import urlencode
     34 

ModuleNotFoundError: No module named 'urlparse'
`

**Comment by xiclopex** [comment]
Any clue?

**Comment by mariorz** [comment]
This library does not yet support Python 3, but will soon, you can help by testing out the PRs https://github.com/bitsoex/bitso-py/pulls :)
