### ISSUE TITLE
Error in price buy order

### ISSUE THREAD

**Issue by GilRobles** [bitsoex/bitso-py#21]
In python a get an error when I try to put a purchase order (error code 22) price error 
market: xrp_btc
Quantity: 1.011888
price: 0.00008 satoshis
Code: order = api.place_order(book='xrp_btc', side='buy', order_type='limit', major=round(1.011888,6), price=0.00008)

ile "C:\bits\personal\BitsoXrpComVenRapida2.0.py", line 128, in BitsoPrincipal
    order = api.place_order(book='xrp_btc', side='buy', order_type='limit', major=round(1.011888,6), price=0.00008)
  File "C:\Python27\lib\site-packages\bitso\api.py", line 513, in place_order
    resp = self._request_url(url, 'POST', params=parameters, private=True)
  File "C:\Python27\lib\site-packages\bitso\api.py", line 906, in _request_url
    data = self._parse_json(resp.content.decode('utf-8'))
  File "C:\Python27\lib\site-packages\bitso\api.py", line 934, in _parse_json
    self._check_for_api_error(data)
  File "C:\Python27\lib\site-packages\bitso\api.py", line 941, in _check_for_api_error
    raise ApiError(data['error'])
bitso.errors.ApiError: {u'message': u'Precio incorrecto', u'code': 22}

**Comment by JuIioCesar** [comment]
Hello @GilRobles. 
Thanks for contributing to the bitso-py repository with this issue report.

From the documentation you can find that we prefer to use strings :

> Precision
> We return decimal numbers as strings to preserve full precision across platforms. We recommend you also convert your numbers to string in order to avoid undesired consequences from precision and truncation errors.

And in the [api tests file](https://github.com/bitsoex/bitso-py/blob/master/tests/test_api.py) you will be able to find more examples on how to use the API like:

`self.api.place_order(book='btc_mxn', side='buy', order_type='limit', major='0.1', price='5600')`

Please let us know if you need help with anything else regarding our API.
