### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by IFFranciscoME** [bitsoex/bitso-py#5]
Estoy teniendo este problema al tratar de instalar el modulo con pip desde la terminal, en una máquina con windows 10 y python 3

Command "python setup.py egg_info" failed with error code 1 in C:\Users\usuario\AppData\Local\Temp\pip-build-hd2m2_54\bitso-py\

Alguna sugerencia ?

**Comment by mariorz** [comment]
Hola Francisco, gracias por reportar. 
La librería es para python 2 :)
