### ISSUE TITLE
Is this compatible with python2, python3, or both?

### ISSUE THREAD

**Issue by norbertbilbeny** [bitsoex/bitso-py#8]
Thank you.

**Comment by mariorz** [comment]
Hi Norberth, it's compatible with Python 2 and currently not compatible with Python 3. Will add to the readme, thanks for asking :)

**Comment by norbertbilbeny** [comment]
Thank you. I'm trying to make it work with Python 3. Which Python 2 version is it exactly? Much appreciated.

**Comment by mariorz** [comment]
Awedome!
Should work on any Python2.X, was developed using 2.7

**Comment by norbertbilbeny** [comment]
Thank you.
